package GUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.UIManager;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Iterator;
import approaches.*;
import objects.Customer;
import objects.CustomerDelta;
import objects.Invitation;
import objects.Item;
import objects.Route;
import objects.VehicleType;
import Fekete.lbFekete;
import IO.InstanceRead;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Huang
 */
public class MainFrame extends javax.swing.JFrame
{

	/**
	 * Creates new form MainFrame
	 */
	public MainFrame()
	{
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{
		setTitle("Main Frame");
		
		runningLabel = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		BrowseButton = new javax.swing.JButton();
		RunButton = new javax.swing.JToggleButton();
		jLabel3 = new javax.swing.JLabel();
		SummaryjLabel4 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		CusInfo_jLabel = new javax.swing.JLabel();
		MapjPanel1 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		VehicleTypejPanel1 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		rectPanel2 = new RectDraw();
		LengthLabel = new javax.swing.JLabel();
		widthLabel = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		nextButton1 = new javax.swing.JButton();
	//	runningDialog.setVisible(false);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(153, 255, 255));
		setPreferredSize(new java.awt.Dimension(1500, 800));
		
		runningLabel.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        runningLabel.setForeground(new java.awt.Color(255, 0, 51));

		jLabel6.setVisible(false);
		nextButton1.setVisible(false);
		// LengthLabel.set
		// rectPanel2.setVisible(false);
		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/GUI/bg-header-logo-ds.png"))); // NOI18N

		jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(255, 51, 255));
		jLabel2.setText("Select Input File:");
		jLabel2.setToolTipText("Select the ****_node.txt file which specifies the customers.");
		jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		BrowseButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		BrowseButton.setForeground(new java.awt.Color(204, 0, 153));
		BrowseButton.setText("Browse");
		BrowseButton.addMouseListener(new java.awt.event.MouseAdapter()
		{
			public void mouseClicked(java.awt.event.MouseEvent evt)
			{

				try
				{
					BrowseButtonMouseClicked(evt);
				}
				catch (FileNotFoundException e)
				{
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});
		

		RunButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/run.png"))); // NOI18N
		
		RunButton.addMouseListener(new java.awt.event.MouseAdapter()
		{
			public void mouseClicked(java.awt.event.MouseEvent evt)
			{

				
					RunButtonMouseClicked(evt);
				
			
			}
		});

		jLabel3.setFont(new java.awt.Font("Wide Latin", 2, 18)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(204, 0, 102));
		jLabel3.setText("RUN");

		SummaryjLabel4.setBackground(new java.awt.Color(153, 255, 255));
		SummaryjLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		SummaryjLabel4.setText("Summary: ");
		SummaryjLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1,
				new java.awt.Color(153,0,255)));

		jScrollPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3,
				new java.awt.Color(255, 0, 255)));
		jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

		CusInfo_jLabel.setBackground(new java.awt.Color(255, 255, 255));
		CusInfo_jLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		CusInfo_jLabel.setText("Customer Info:");
		CusInfo_jLabel.setToolTipText("");
		CusInfo_jLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
		CusInfo_jLabel.setAutoscrolls(true);
		CusInfo_jLabel.setOpaque(true);
		jScrollPane1.setViewportView(CusInfo_jLabel);

		MapjPanel1.setBackground(new java.awt.Color(255, 255, 255));
		MapjPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3,
				new java.awt.Color(255, 0, 255)));
		MapjPanel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

		jLabel4.setBackground(new java.awt.Color(255, 255, 255));
		jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jLabel4.setText("Map:");
		jLabel4.setOpaque(true);

		/*
		 * javax.swing.GroupLayout MapjPanel1Layout = new
		 * javax.swing.GroupLayout(MapjPanel1);
		 * MapjPanel1.setLayout(MapjPanel1Layout);
		 * MapjPanel1Layout.setHorizontalGroup(
		 * MapjPanel1Layout.createParallelGroup
		 * (javax.swing.GroupLayout.Alignment.LEADING)
		 * .addGroup(MapjPanel1Layout.createSequentialGroup()
		 * .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68,
		 * javax.swing.GroupLayout.PREFERRED_SIZE) .addGap(0, 668,
		 * Short.MAX_VALUE)) ); MapjPanel1Layout.setVerticalGroup(
		 * MapjPanel1Layout
		 * .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		 * .addGroup(MapjPanel1Layout.createSequentialGroup()
		 * .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
		 * javax.swing.GroupLayout.PREFERRED_SIZE)
		 * .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
		 * Short.MAX_VALUE)) );
		 */
		MapjPanel1.setLayout(null);
		MapjPanel1.setPreferredSize(new Dimension(620, 590));

		jLabel4.setLocation(3, 3);
		jLabel4.setSize(68, 25);
		// jLabel4.repaint();

		// jLabel4.setVisible(true);;
		MapjPanel1.add(jLabel4);
		// MapjPanel1.revalidate();
		// MapjPanel1.repaint();

		VehicleTypejPanel1.setBackground(new java.awt.Color(255, 255, 255));
		VehicleTypejPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3,
				new java.awt.Color(255, 0, 255)));
		VehicleTypejPanel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

		jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel5.setText("VehicleType:");
		
//		rectPanel2.setOpaque(isOpaque);

		rectPanel2.setBackground(new java.awt.Color(255, 255, 255));
		rectPanel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

		javax.swing.GroupLayout rectPanel2Layout = new javax.swing.GroupLayout(rectPanel2);
		rectPanel2.setLayout(rectPanel2Layout);
		rectPanel2Layout.setHorizontalGroup(rectPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 261, Short.MAX_VALUE));
		rectPanel2Layout.setVerticalGroup(rectPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 201, Short.MAX_VALUE));

		LengthLabel.setBackground(new java.awt.Color(255, 255, 255));
		LengthLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		LengthLabel.setForeground(new java.awt.Color(0, 51, 51));
		LengthLabel.setOpaque(true);

		widthLabel.setBackground(new java.awt.Color(255, 255, 255));
		widthLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		widthLabel.setForeground(new java.awt.Color(0, 51, 51));
		widthLabel.setOpaque(true);

		jLabel6.setBackground(new java.awt.Color(255, 255, 255));
		jLabel6.setFont(new java.awt.Font("Aharoni", 0, 12)); // NOI18N
		jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/truckhead.png"))); // NOI18N
		jLabel6.setOpaque(true);

		nextButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		nextButton1.setText("Next");
		nextButton1.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				nextButton1MouseClicked(evt);
			}
		});

		/*javax.swing.GroupLayout VehicleTypejPanel1Layout = new javax.swing.GroupLayout(
				VehicleTypejPanel1);
		VehicleTypejPanel1.setLayout(VehicleTypejPanel1Layout);
		VehicleTypejPanel1Layout
				.setHorizontalGroup(VehicleTypejPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								VehicleTypejPanel1Layout
										.createSequentialGroup()
										.addGroup(
												VehicleTypejPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																VehicleTypejPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel5,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				113,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(0, 0,
																				Short.MAX_VALUE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																VehicleTypejPanel1Layout
																		.createSequentialGroup()
																		.addGap(0, 0,
																				Short.MAX_VALUE)
																		.addComponent(
																				widthLabel,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				43,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(rectPanel2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel6,
												javax.swing.GroupLayout.PREFERRED_SIZE, 119,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(nextButton1).addGap(130, 130, 130))
						.addGroup(
								VehicleTypejPanel1Layout
										.createSequentialGroup()
										.addGap(248, 248, 248)
										.addComponent(LengthLabel,
												javax.swing.GroupLayout.PREFERRED_SIZE, 53,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		VehicleTypejPanel1Layout
				.setVerticalGroup(VehicleTypejPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								VehicleTypejPanel1Layout
										.createSequentialGroup()
										.addComponent(jLabel5,
												javax.swing.GroupLayout.PREFERRED_SIZE, 25,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(98, 98, 98)
										.addComponent(widthLabel,
												javax.swing.GroupLayout.PREFERRED_SIZE, 62,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								VehicleTypejPanel1Layout
										.createSequentialGroup()
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(LengthLabel,
												javax.swing.GroupLayout.PREFERRED_SIZE, 34,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												VehicleTypejPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																VehicleTypejPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(
																				VehicleTypejPanel1Layout
																						.createSequentialGroup()
																						.addComponent(
																								rectPanel2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGap(46,
																								46,
																								46))
																		.addGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				VehicleTypejPanel1Layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel6,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								154,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGap(75,
																								75,
																								75)))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																VehicleTypejPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				nextButton1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				42,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(128, 128, 128)))));*/
		
		  javax.swing.GroupLayout VehicleTypejPanel1Layout = new javax.swing.GroupLayout(VehicleTypejPanel1);
	        VehicleTypejPanel1.setLayout(VehicleTypejPanel1Layout);
	        VehicleTypejPanel1Layout.setHorizontalGroup(
	            VehicleTypejPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VehicleTypejPanel1Layout.createSequentialGroup()
	                .addGap(0, 0, Short.MAX_VALUE)
	                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(49, 49, 49))
	            .addGroup(VehicleTypejPanel1Layout.createSequentialGroup()
	                .addGroup(VehicleTypejPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(VehicleTypejPanel1Layout.createSequentialGroup()
	                        .addGap(63, 63, 63)
	                        .addComponent(widthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                        .addComponent(rectPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                        .addComponent(nextButton1))
	                    .addGroup(VehicleTypejPanel1Layout.createSequentialGroup()
	                        .addGap(287, 287, 287)
	                        .addComponent(LengthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	        );
	        VehicleTypejPanel1Layout.setVerticalGroup(
	            VehicleTypejPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(VehicleTypejPanel1Layout.createSequentialGroup()
	                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(18, 18, 18)
	                .addGroup(VehicleTypejPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(VehicleTypejPanel1Layout.createSequentialGroup()
	                        .addGap(73, 73, 73)
	                        .addComponent(widthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
	                    .addGroup(VehicleTypejPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                        .addGroup(VehicleTypejPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(rectPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VehicleTypejPanel1Layout.createSequentialGroup()
	                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addGap(25, 25, 25)))
	                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VehicleTypejPanel1Layout.createSequentialGroup()
	                            .addComponent(nextButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addGap(78, 78, 78))))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(LengthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(17, Short.MAX_VALUE))
	        );

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING, false)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		MapjPanel1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						jScrollPane1,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						614,
																						Short.MAX_VALUE)
																				.addComponent(
																						VehicleTypejPanel1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						614,
																						Short.MAX_VALUE)))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						SummaryjLabel4,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel1)
																								.addGap(39,
																										39,
																										39)
																								.addComponent(
																										jLabel2,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										171,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										BrowseButton,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										84,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addGap(172,
																										172,
																										172)
																								.addComponent(
																										RunButton,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										50,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										jLabel3,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										87,
																										javax.swing.GroupLayout.PREFERRED_SIZE)))
																.addGap(18, 18, 18)
																.addComponent(
																		runningLabel,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		499, Short.MAX_VALUE)))
								.addContainerGap(160, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addContainerGap()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														jLabel1,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														83,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addGroup(
																														layout.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.BASELINE)
																																.addComponent(
																																		jLabel2,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		66,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addComponent(
																																		BrowseButton,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		45,
																																		javax.swing.GroupLayout.PREFERRED_SIZE))))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(23,
																										23,
																										23)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING)
																												.addComponent(
																														RunButton,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														40,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														jLabel3,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														41,
																														javax.swing.GroupLayout.PREFERRED_SIZE))))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		SummaryjLabel4,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		41,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(23, 23, 23)
																.addComponent(
																		runningLabel,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		117,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING, false)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jScrollPane1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		288,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		VehicleTypejPanel1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(MapjPanel1,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE))
								.addContainerGap(34, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void nextButton1MouseClicked(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_nextButton1ActionPerformed
		vehicletypeindex++;
		vehicletypeindex = vehicletypeindex % (vehicleTypes.size());
		int length = vehicleTypes.get(vehicletypeindex).get_length();
		int width = vehicleTypes.get(vehicletypeindex).get_width();
		rectPanel2.setSize(length, width);
		rectPanel2.repaint();
		// rectPanel2.setVisible(true);
		// nextButton1.setVisible(true);
		// jLabel6.setVisible(true);
		VehicleType vehicleType = vehicleTypes.get(vehicletypeindex);
		
		jLabel5.setText("VehicleType" + vehicletypeindex + ": Capacity "+vehicleType.get_capacity()+", fixedCost "+vehicleType.get_fixedCost()+", variableCost "+vehicleType.get_variableCost());
		LengthLabel.setText("" + length);
		widthLabel.setText("" + width);

	}// GEN-LAST:event_nextButton1ActionPerformed

	

	private void BrowseButtonMouseClicked(java.awt.event.MouseEvent evt)
			throws FileNotFoundException
	{// GEN-FIRST:event_BrowseButtonMouseClicked
		// TODO add your handling code here:
//		UIManager.put("FileChooser.readOnly", Boolean.TRUE); 
		JFileChooser chooser = new JFileChooser();

		int returnVal = chooser.showOpenDialog(BrowseButton);
		if (returnVal == JFileChooser.APPROVE_OPTION)
		{
			jLabel4.setVisible(false);
			if (!justOpen)
			{
				for (Iterator iterator = customerLabels.iterator(); iterator.hasNext();)
				{
					CustomerLabel customerLabel=(CustomerLabel) iterator.next();
					JLabel jLabel = customerLabel.getLabel();
					MapjPanel1.remove(jLabel);
					iterator.remove();
				}
				// remove old jlabels,
			}
			// use new jlabels, defferent color depot,
			File inputFile = chooser.getSelectedFile();
			InstanceRead instanceReader = new InstanceRead(inputFile);
			routes=new ArrayList<Route>();
			vehicleTypes = instanceReader.readVehicles();

			customers = instanceReader.readCustomers(vehicleTypes);
			depot = customers.remove(0);

			StringBuffer customerSB = new StringBuffer();
			int quantityOfItems = SupportMainFrame.handle_customerSB(customerSB, customers);
			SummaryjLabel4.setText("Summary: We need to deliver " + quantityOfItems + " items to "
					+ customers.size() + " customers, using " + vehicleTypes.size()
					+ " types of vehicles.");
			CusInfo_jLabel.setText(customerSB.toString());
			Collections.sort(customers, Customer.sort_by_suitablescore);

			// vpanel.setPreferredSize(new Dimension(50,50));
			// VehicleTypejPanel1.add(new RectDraw());
			vehicletypeindex = 0;
			VehicleType vehicleType = vehicleTypes.get(0);
			// VehicleTypejPanel1.validate();
			int length = vehicleTypes.get(0).get_length();
			int width = vehicleTypes.get(0).get_width();
			rectPanel2.setSize(length, width);
			rectPanel2.repaint();
			// rectPanel2.setVisible(true);
			nextButton1.setVisible(true);
			jLabel6.setVisible(true);
			jLabel5.setText("VehicleType" + vehicletypeindex + ": Capacity "+vehicleType.get_capacity()+", fixedCost "+vehicleType.get_fixedCost()+", variableCost factor "+vehicleType.get_variableCost());
			LengthLabel.setText("" + length);
			widthLabel.setText("" + width);
			// rectPanel2.repaint();
			int[] coorLimt = SupportMainFrame.findCoordinatesLimits(depot, customers);
			SupportMainFrame.addPointforDepot(depot, MapjPanel1, customerLabels, coorLimt);
			for (Customer customer : customers)
			{
				SupportMainFrame.addPointforCus(customer, MapjPanel1, customerLabels, coorLimt);
			}
			MapjPanel1.revalidate();
			MapjPanel1.repaint();
			justOpen = false;

		}
	}// GEN-LAST:event_BrowseButtonMouseClicked
	 
	public void changeColor(ArrayList<Customer> customerSequence)
	{
		for (Customer customer : customerSequence)
		{
			for (CustomerLabel customerLabel : customerLabels)
			{
				if(customerLabel.getCustomer()==customer)
				{
					customerLabel.getLabel().setBackground(new Color(255, 0, 51));
					customerLabel.getLabel().setSize(10, 10);
//					customerLabel.getLabel().revalidate();
//					customerLabel.getLabel().repaint();
//					customerLabel.getLabel().getParent().revalidate();
//					customerLabel.getLabel().getParent().repaint();
					
					break;
				}
			}
		}
	}
	
	public void recoverColor(ArrayList<Customer> customerSequence)
	{
		for (Customer customer : customerSequence)
		{
			for (CustomerLabel customerLabel : customerLabels)
			{
				if(customerLabel.getCustomer()==customer)
				{
					customerLabel.getLabel().setBackground(new Color(0,0,255));;
					customerLabel.getLabel().setSize(6, 6);
					break;
				}
			}
		}
	}

	private void RunButtonMouseClicked(java.awt.event.MouseEvent evt)
	{
		if(vehicleTypes!=null)
		{
//		runningDialog.setVisible(true);
		//runningDialog.revalidate();
//		runningDialog.repaint();
		BrowseButton.setVisible(false);
		RunButton.setVisible(false);
		jLabel3.setVisible(false);
//		runningLabel.setText("Running......This may take a while. Please wait!");
		
//		nextButton1.setEnabled(false);
		
		//calculation start
		if(customers.size()!=0)
			SupportMainFrame.calculate(customers, routes, vehicleTypes, depot);
		//calculation over
		
//		runningDialog.setVisible(false);;
       ResultJFrame resultJFrame = new ResultJFrame();
       resultJFrame.setOwner(this);
      
       resultJFrame.addWindowListener(new WindowAdapter()
	{
    	   public void windowClosed(WindowEvent e) {
    	        resultFrameClosed(e);
    	    }
	});
       resultJFrame.initRoutesAndVehicles(routes, vehicleTypes,depot);
       resultJFrame.setInitShow();
       resultJFrame.setVisible(true);
       
        
		}
	}
	
	private void   resultFrameClosed(WindowEvent e)
	{
		BrowseButton.setVisible(true);
		RunButton.setVisible(true);
		jLabel3.setVisible(true);
	}
	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[])
	{
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */

		try
		{
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels())
			{
				if ("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		}
		catch (ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		catch (InstantiationException ex)
		{
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		catch (IllegalAccessException ex)
		{
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		catch (javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{

				MainFrame mainFrame = new MainFrame();

				mainFrame.setVisible(true);
				// LoginDialog loginDlg = new LoginDialog(mainFrame);

				// loginDlg.setVisible(true);
			}
		});
	}

	private static ArrayList<Customer> customers;
	private static ArrayList<Route> routes = new ArrayList<Route>();
	private static ArrayList<VehicleType> vehicleTypes;
	private static Customer depot;

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton BrowseButton;
	private javax.swing.JLabel CusInfo_jLabel;
	private javax.swing.JLabel LengthLabel;
	private javax.swing.JPanel MapjPanel1;
	private javax.swing.JToggleButton RunButton;
	private javax.swing.JLabel SummaryjLabel4;
	private javax.swing.JPanel VehicleTypejPanel1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JButton nextButton1;
	private RectDraw rectPanel2;
	private javax.swing.JLabel widthLabel;
	private int vehicletypeindex = 0;
	private boolean justOpen = true;
	private ArrayList<CustomerLabel> customerLabels = new ArrayList<CustomerLabel>();
	private javax.swing.JLabel runningLabel;
//	private RunningDialog runningDialog = new RunningDialog(this);
	// End of variables declaration//GEN-END:variables
}
